DROP SCHEMA IF EXISTS player CASCADE;

CREATE SCHEMA player;

CREATE TABLE player.player (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    USER_ID UUID NOT NULL,
    NAME VARCHAR NOT NULL,
    CASH INT NOT NULL DEFAULT 0
);

ALTER TABLE player.player ADD UNIQUE (USER_ID, NAME);

GRANT ALL PRIVILEGES ON SCHEMA player to "player-user";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA player TO "player-user";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA player TO "player-user";