DROP SCHEMA IF EXISTS auth CASCADE;

CREATE SCHEMA auth;

CREATE TABLE auth.user (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NAME VARCHAR NOT NULL,
    HASH VARCHAR NOT NULL
);

GRANT ALL PRIVILEGES ON SCHEMA auth to "auth-user";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA auth TO "auth-user";