DROP SCHEMA IF EXISTS truck CASCADE;

CREATE SCHEMA truck;

CREATE TABLE truck.navigation (
    ID SERIAL PRIMARY KEY,
    TRUCK_ID VARCHAR NOT NULL,
    CURRENT_CITY_ID VARCHAR NOT NULL DEFAULT 'MOON',
    START_TIME BIGINT NOT NULL DEFAULT -1,
    ARRIVAL_TIME BIGINT NOT NULL DEFAULT -1,
    NEXT_CITY_ID VARCHAR
);

GRANT ALL PRIVILEGES ON SCHEMA truck to "truck-user";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA truck TO "truck-user";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA truck TO "truck-user";