DROP SCHEMA IF EXISTS truck CASCADE;

CREATE SCHEMA truck;

CREATE TABLE truck.navigation (
    ID SERIAL PRIMARY KEY,
    TRUCK_ID UUID NOT NULL,
    CURRENT_CITY_ID VARCHAR NOT NULL DEFAULT 'MOON',
    START_TIME BIGINT NOT NULL DEFAULT -1,
    ARRIVAL_TIME BIGINT NOT NULL DEFAULT -1,
    NEXT_CITY_ID VARCHAR
);

CREATE TABLE truck.truck (
    ID UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    TEMPLATE_ID VARCHAR NOT NULL,
    PLAYER_ID UUID NOT NULL,
    NAME VARCHAR NOT NULL,
    TEXTURE VARCHAR NOT NULL,
    SPEED INT NOT NULL DEFAULT 0,
    STORAGE JSONB NOT NULL
);

CREATE TABLE truck.player (
    ID UUID NOT NULL PRIMARY KEY,
    INITIALIZED BOOLEAN NOT NULL DEFAULT FALSE
);

GRANT ALL PRIVILEGES ON SCHEMA truck to "truck-user";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA truck TO "truck-user";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA truck TO "truck-user";