DROP SCHEMA IF EXISTS clock CASCADE;

CREATE SCHEMA clock;

CREATE TABLE clock.clock (
    ID INT NOT NULL PRIMARY KEY,
    START_TIME BIGINT NOT NULL DEFAULT 0,
    TIME_MULTIPLIER INT NOT NULL DEFAULT 60
);

INSERT INTO clock.clock (ID, START_TIME, TIME_MULTIPLIER) VALUES (1, 0, 60);

GRANT ALL PRIVILEGES ON SCHEMA clock to "clock-user";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA clock TO "clock-user";