export const FACTORY_ADDED = "FACTORY_ADDED";
export const RESOURCE_PRODUCED = "RESOURCE_PRODUCED";
export const STORAGE_CONTENT_CHANGED = "STORAGE_CONTENT_CHANGED";
export const RESOURCE_STORAGE_CAPACITY_CHANGED =
  "RESOURCE_STORAGE_CAPACITY_CHANGED";
export const PRODUCTION_FINISHED = "PRODUCTION_FINISHED";
export const PRODUCTION_STARTED = "PRODUCTION_STARTED";
export const RESOURCE_SOLD = "RESOURCE_SOLD";
export const RESOURCE_PRICE_CHANGED = "RESOURCE_PRICE_CHANGED";
export const PRODUCTION_LINE_ADDED = "PRODUCTION_LINE_ADDED";
